name: iOS Build

on:
  push:
    branches: [ "main" ] # Updated to main
  pull_request:
    branches: [ "main" ] # Updated to main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - List Files
        run: ls -R

      - name: Build for Simulator
        # Ensure this matches the folder name in your repo
        working-directory: HelloWorldSwiftUI 
        run: |
          xcodebuild build \
            -project "HelloWorldSwiftUI.xcodeproj" \
            -scheme "HelloWorldSwiftUI" \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO
